### PR TITLE
pull in some upstream sdbusplus changes

### PR DESCRIPTION
**Pull request by geissonator**
This is a selective pull in of some changes from upstream to ensure this
repo continues to compile against upstream CI

Pulled from the following:
  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/50010
  https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/52644

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>

### CODE REVIEW

**Comment by geissonator** [comment]
jenkins run tests please

**Comment by geissonator** [comment]
I'm not sure what to do about this CI fail, it's unrelated to the changes in this commit:
```
checking for jsmn... no
configure: error: Package requirements (jsmn) were not met:
```
Basically we have some downstream code that uses jsmn and I can't seem to find a way to get it installed in the CI container. I tried just doing an apt install of libjsmn-dev and also manually copied the jsmn.h file in but no luck.

**Comment by geissonator** [comment]
As this is just pulling some already-merged upstream changes, I'm going to go ahead and merge this.

**Review by joseph-reynolds — COMMENTED** [review]
Seems okay to me.  The jsmn package is used downstream by the bmc-acf service.

**Pull request merged**
